openapi: 3.0.1
info:
  title: CSP api文档
  description: 资金结算系统
  termsOfService: http://www.99fund.com
  version: 2.0.0
servers:
- url: http://localhost:12888/
tags:
- name: fund-settlement-param-controller
  description: Fund Settlement Param Controller
- name: fund-param-controller
  description: Fund Param Controller
paths:
  /csp/v1/parameter/handle/fund/queryOne:
    get:
      tags:
      - fund-param-controller
      description: 查询单个基金
      operationId: queryFundUsingGET
      parameters:
      - name: fundCode
        in: query
        description: 基金代码
        required: true
        schema:
          type: string
      - name: status
        in: query
        description: '处理状态: 1-待复核, 2-已复核'
        required: true
        schema:
          type: string
      - name: querySign
        in: query
        description: '查询标识: 可选SUMMARY:已生效数据, OPERATE:待复核数据, CHECK:待复核数据'
        required: true
        schema:
          type: string
      responses:
        200:
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Response«QsFundInfoDetailsPo»'
        401:
          description: Unauthorized
          content: {}
        403:
          description: Forbidden
          content: {}
        404:
          description: Not Found
          content: {}
  /csp/v1/parameter/handle/fundSettlement/one:
    get:
      tags:
      - fund-settlement-param-controller
      description: 查询单条基金资金交收配置
      operationId: selectOneUsingGET
      parameters:
      - name: fundCode
        in: query
        description: 基金代码
        required: true
        schema:
          type: string
      - name: status
        in: query
        description: '处理状态: 1-待复核, 2-已复核'
        required: true
        schema:
          type: string
      - name: querySign
        in: query
        description: '查询标识: 可选SUMMARY:已生效数据, OPERATE:待复核数据, CHECK:待复核数据'
        required: true
        schema:
          type: string
      responses:
        200:
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Response«FundInfoExtDetailDto»'
        401:
          description: Unauthorized
          content: {}
        403:
          description: Forbidden
          content: {}
        404:
          description: Not Found
          content: {}
components:
  schemas:
    AgencySettlement:
      type: object
      properties:
        configId:
          type: string
          description: 模板编号
        organ:
          type: array
          description: 机构列表
          items:
            type: string
    AgencySettlementConfigDto:
      type: object
      properties:
        defaultSettlement:
          type: string
        organConfigs:
          type: array
          description: 机构交收列表
          items:
            $ref: '#/components/schemas/AgencySettlement'
    FundInfoExtDetailDto:
      required:
      - fundcode
      - qsFundInfoDto
      type: object
      properties:
        agencySettlementConfigDto:
          $ref: '#/components/schemas/AgencySettlementConfigDto'
        checker:
          type: string
          description: 复合人
        fundAgencyPaydayPoList:
          type: array
          description: 交收日期配置
          items:
            $ref: '#/components/schemas/资金交收天数配置'
        fundcode:
          type: string
          description: 产品代码
        handleserialno:
          type: string
          description: 经办流水号
        innerSettlementConfigDto:
          $ref: '#/components/schemas/AgencySettlementConfigDto'
        inserttimestamp:
          type: string
          description: 新增时间
        operator:
          type: string
          description: 经办人
        qsFundInfoDetailsPo:
          $ref: '#/components/schemas/QsFundInfoDetailsPo'
        qsFundInfoDto:
          $ref: '#/components/schemas/产品信息'
        status:
          type: string
          description: 处理状态
        trusteetplcode:
          type: string
          description: 托管行交收
        updatetimestamp:
          type: string
          description: 更新时间
        zdSign:
          type: string
          description: 中登标识
      description: 产品信息及资金交收配置明细
    QsFundInfoDetailsPo:
      type: object
      properties:
        checker:
          type: string
          description: 复合人
        currency:
          type: string
        datasource:
          type: string
        fchangefund:
          type: string
        fczlx:
          type: string
        fdesc:
          type: string
        ffounddate:
          type: string
        ffundcode:
          type: string
        ffundname:
          type: string
        ffundnameabbr:
          type: string
        ffundnumber:
          type: string
        ffundstate:
          type: string
        ffundstatus:
          type: string
        ffundtype:
          type: string
        fjzfund:
          type: string
        fmarketid:
          type: string
        fmjjzr:
          type: string
        fsedate:
          type: string
        fzdyfundtype:
          type: string
        handleserialno:
          type: string
          description: 经办流水号
        inserttimestamp:
          type: string
          description: 新增时间
        investment:
          type: string
        isetf:
          type: string
        isfof:
          type: string
        isinitiate:
          type: string
        isqdii:
          type: string
        maincode:
          type: string
        operationmode:
          type: string
        operator:
          type: string
          description: 经办人
        status:
          type: string
          description: 处理状态
        tano:
          type: string
        updatetimestamp:
          type: string
          description: 更新时间
    Response«FundInfoExtDetailDto»:
      type: object
      properties:
        body:
          $ref: '#/components/schemas/FundInfoExtDetailDto'
        returnCode:
          type: integer
          format: int32
        returnMsg:
          type: string
        returnType:
          type: string
    Response«QsFundInfoDetailsPo»:
      type: object
      properties:
        body:
          $ref: '#/components/schemas/QsFundInfoDetailsPo'
        returnCode:
          type: integer
          format: int32
        returnMsg:
          type: string
        returnType:
          type: string
    产品信息:
      required:
      - currency
      - ffundcode
      - ffundname
      - ffundnameabbr
      - ffundstatus
      - ffundtype
      - investment
      - isetf
      - isfof
      - isinitiate
      - isqdii
      - maincode
      - operationmode
      - tano
      type: object
      properties:
        currency:
          type: string
          description: 币种
        ffounddate:
          type: string
          description: 产品成立日
        ffundcode:
          type: string
          description: 产品代码
        ffundname:
          type: string
          description: 产品名称
        ffundnameabbr:
          type: string
          description: 基金简称
        ffundstatus:
          type: string
          description: 产品状态
        ffundtype:
          type: string
          description: 产品类型
        fmarketid:
          type: string
          description: 节假日
        fmjjzr:
          type: string
          description: 募集截止日期
        fsedate:
          type: string
          description: 募集起始日期
        fzdyfundtype:
          type: string
          description: 自定义类型
        investment:
          type: string
          description: 投资对象
        isetf:
          type: string
          description: 是否场内
        isfof:
          type: string
          description: 是否FOF
        isinitiate:
          type: string
          description: 是否发起式
        isqdii:
          type: string
          description: 是否QDII
        maincode:
          type: string
          description: 产品主代码
        operationmode:
          type: string
          description: 运作模式
        tano:
          type: string
          description: TA代码
    资金交收天数配置:
      required:
      - ffundcode
      - fjsdate
      - ftgjsdate
      - ftradetype
      type: object
      properties:
        busitag:
          type: string
          description: 业务标识
        datasource:
          type: string
          description: 数据源
        enddate:
          type: string
          description: 结束日期
        fcompfunds:
          type: string
          description: 交收模式
        ffundcode:
          type: string
          description: 基金代码
        fjsdate:
          type: string
          description: 交收日期
        fjzfund:
          type: string
          description: 基准基金
        fmjrate:
          type: number
          description: 募集期利率
        fqrdate:
          type: string
          description: 确认日期
        ftgjsdate:
          type: string
          description: 托管行交收日期
        ftradetype:
          type: string
          description: 交易类型
        fundname:
          type: string
          description: 基金名称
        fyzdate:
          type: string
          description: 验资日
        organCodeList:
          type: array
          description: 机构列表
          items:
            type: string
        startdate:
          type: string
          description: 起始日期
